version: '3.8'

services:
  obsidian-remote:
    image: ghcr.io/sytone/obsidian-remote:latest
    container_name: obsidian-remote
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/config  # Используем совместный том
    restart: always

  flashcarder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcarder
    ports:
      - "8888:8081"
    depends_on:
      - obsidian-remote
    volumes:
      - shared-data:/config  # Используем тот же совместный том

volumes:
  shared-data:  # Определение совместного тома
