version: '3.8'

services:
  flashcarder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcarder
    ports:
      - "8888:8081"
    volumes:
      - type: bind
        source: ./flashcards
        target: ./
