version: '3.8'

services:
  flashcarder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcarder
    ports:
      - "8888:8081"
    volumes:
      - ./flashcards:/app/flashcards
      - ./flashcards/audio:/app/flashcards/audio
      - ./flashcards/images:/app/flashcards/images
